<?php

namespace App\AI\Tools;

use App\Models\Document;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use LaravelAIAgent\Attributes\AsAITool;

class GenerateIllustratedGuideImageTool
{
    #[AsAITool('Generate an illustrated “screenshot-like” SVG image for a guide (click-path/steps diagram)')]
    public function generate(
        string $title,
        array $steps,
        string $context = 'guide'
    ): array {
        $title = trim($title);
        $context = trim($context);

        if ($title === '') {
            return ['ok' => false, 'reason' => 'Missing title'];
        }

        $steps = array_values(array_filter($steps, fn ($s) => is_string($s) && trim($s) !== ''));
        if (count($steps) === 0) {
            return ['ok' => false, 'reason' => 'Missing steps'];
        }

        $imageWidth = 960;
        $imagePadding = 24;
        $cardW = 880;
        $cardX = ($imageWidth - $cardW) / 2;

        $cardXPlus20 = $cardX + 20;
        $cardXPlus42 = $cardX + 42;
        $cardXPlus90 = $cardX + 90;

        $maxStepsToRender = 8;
        $steps = array_slice($steps, 0, $maxStepsToRender);

        // Deterministic brutalist SVG (no external image provider needed)
        // Colors: black outline, flat fills.
        $svgSteps = '';
        foreach ($steps as $idx => $step) {
            $n = $idx + 1;
            $y = 180 + ($idx * 84);
            $yPlus18 = $y + 18;
            $yPlus48 = $y + 48;
            $yPlus47 = $y + 47;
            $label = htmlspecialchars($n . '');
            $text = htmlspecialchars(trim($step));

            $svgSteps .= <<<SVG
  <g>
    <rect x="{$cardX}" y="{$y}" width="{$cardW}" height="72" rx="16" ry="16" fill="#ffffff" stroke="#000000" stroke-width="4"/>
    <rect x="{$cardXPlus20}" y="{$yPlus18}" width="44" height="44" rx="12" ry="12" fill="#dc2626" stroke="#000000" stroke-width="4"/>
    <text x="{$cardXPlus42}" y="{$yPlus48}" font-family="Arial, sans-serif" font-size="22" font-weight="800" text-anchor="middle" fill="#ffffff">{$label}</text>
    <text x="{$cardXPlus90}" y="{$yPlus47}" font-family="Arial, sans-serif" font-size="22" font-weight="600" dominant-baseline="middle" fill="#000000">{$text}</text>
  </g>
SVG;
        }

        $svgH = 180 + (count($steps) * 84) + 120;

        $halfWidth = $imageWidth / 2;
        $footerY = $svgH - 46;

        $safeContext = htmlspecialchars($context);
        $safeTitle = htmlspecialchars($title);

        $svg = <<<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="{$imageWidth}" height="{$svgH}" viewBox="0 0 {$imageWidth} {$svgH}">
  <rect x="0" y="0" width="{$imageWidth}" height="{$svgH}" fill="#fff7ed" stroke="#000000" stroke-width="6"/>

  <!-- Header -->
  <rect x="{$cardX}" y="22" width="{$cardW}" height="120" rx="28" ry="28" fill="#ffffff" stroke="#000000" stroke-width="6"/>
  <text x="{$halfWidth}" y="78" font-family="Arial, sans-serif" font-size="40" font-weight="900" text-anchor="middle" fill="#000000">{$safeTitle}</text>
  <text x="{$halfWidth}" y="120" font-family="Arial, sans-serif" font-size="22" font-weight="700" text-anchor="middle" fill="#dc2626">{$safeContext}</text>

  <!-- Steps -->
{$svgSteps}

  <!-- Footer -->
  <text x="{$halfWidth}" y="{$footerY}" font-family="Arial, sans-serif" font-size="18" font-weight="700" text-anchor="middle" fill="#000000">Generated by Coin Security Help Assistant</text>
</svg>
SVG;

        // Persist as a Document (SVG file)
        $slug = Str::slug($title);
        $doc = new Document();
        $doc->title = $title . ' - Guide Image';
        $doc->description = 'Illustrated guide image generated by AI (SVG).';
        $doc->original_filename = $slug . '.svg';
        $doc->mime_type = 'image/svg+xml';
        $doc->file_type = 'image';
        $doc->file_size = Str::length($svg);
        $doc->file_path = '';

        // Minimal required categorization fields (if your schema enforces them)
        $doc->category_id = null;
        $doc->uploaded_by = auth()?->id();
        $doc->module = 'help';
        $doc->department = null;
        $doc->access_level = 'private';
        $doc->tags = ['ai', 'guide', 'illustration'];

        // Save first to get an id (some columns may need it)
        $doc->save();

        $dir = 'ai-guides/' . $doc->id;
        $fileName = $slug . '-' . $doc->id . '.svg';
        $relativePath = $dir . '/' . $fileName;

        Storage::disk('public')->put($relativePath, $svg);

        $doc->file_path = $relativePath;
        $doc->save();

        $url = Storage::disk('public')->url($relativePath);

        return [
            'ok' => true,
            'document_id' => $doc->id,
            'url' => $url,
            'mime_type' => $doc->mime_type,
        ];
    }

    private function htmlspecialchars(string $value): string
    {
        return str_replace(
            ['&', '<', '>', '"', "'"],
            ['&', '<', '>', '"', '&#039;'],
            $value
        );
    }
}
