export interface GuardFormData {
    employee_id: string;
    name: string;
    phone: string;
    email: string;
    address: string;
    residence_address?: string;
    residence_city?: string;
    residence_district?: string;
    id_number?: string;
    date_of_birth: string;
    gender: string;
    marital_status?: 'single' | 'married' | 'divorced' | 'widowed' | '';
    spouse_name?: string;
    spouse_phone?: string;
    emergency_contact_name?: string;
    emergency_contact_phone?: string;
    next_of_kin_name?: string;
    next_of_kin_relationship?: string;
    next_of_kin_phone?: string;
    supervisor_id: string;
    hire_date: string;
    guard_type: 'permanent' | 'standby' | 'reliever';
    guard_grade_id?: string;
    home_village?: string;
    home_ta?: string;
    home_district?: string;
    education_level?: string;
    qualifications?: any;
    languages?: any;
    dependents_count?: string | number;
    children_names?: string;
    notes: string;
    status: 'active' | 'inactive' | 'suspended' | 'dismissed' | 'absconded';
    employee_role?: 'guard' | 'driver';
    client_id?: string;
}